@AOAI_Workshop_HostAddress = http://localhost:5280

POST {{AOAI_Workshop_HostAddress}}/chat/
Content-Type: application/json

{
    "history": [],
    "prompt": "why is the sky blue"
}
###

POST {{AOAI_Workshop_HostAddress}}/chat/
Content-Type: application/json

{
    "history": [
        {"content":"who won the last super bowl","role":"user"},
        {"content":"Super Bowl LVII, was won by the Kansas City Chiefs","role":"agent"}
    ],
    "prompt": "What colors are their jerseys"
}

###
//No bbody,  should get a 400 Bad Request
POST {{AOAI_Workshop_HostAddress}}/chat/
Content-Type: application/json

###
POST https://prod-11.westus.logic.azure.com:443/workflows/8b7c8ee716274559b959608da21ef99a/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=TWmN6H1NST8LU0NF_oet6FEH8OCYLXEEnOgG0GWLRBs
Content-Type: application/json

{
    "City": "Seattle",
    "State": "Washington",
    "Zip": "98101"
}

###
GET https://prod-11.westus.logic.azure.com:443/workflows/8b7c8ee716274559b959608da21ef99a/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=TWmN6H1NST8LU0NF_oet6FEH8OCYLXEEnOgG0GWLRBs
Content-Type: application/json
